default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: postgres
  user: postgres

development:
  <<: *default
  database: dev
test:
  <<: *default
  database: tendtime-server_test
production:
  <<: *default
  database: tendtime-server_production
  username: tendtime-server
  password: <%= ENV['TENDTIME-SERVER_DATABASE_PASSWORD'] %>
